### ISSUE TITLE
Field API feedback

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-php#27]
# Overview

Based on this readme listing I'm adding feedback based on existent implementations and expected lib user competencies (as we target many almost non-tech users - publisher, data wranglers etc).

```php
$filed = new FieldsFactory::field((object)["name" => "id", "type" => "integer"])
```

### Factory class?

I think it's good for programmers but non-tech users more prefer to don't have a deal with advanced programming concepts. Technically it should not  be different but as a {USER} I'd more like to have just `$field = new Field($descriptor)` or `$field = Field.create/load($descriptor)`.

**Comment by OriHoch** [comment]
in latest release, the FieldsFactory was removed from README

non tech users should not use the Field object directly, they will use the Schema

```php
$schema = new Schema(["fields" => [
  ["name" => "id", "type" => "integer"]
]]);
```

or add fields like this:

```php
$schema->field("title", ["type" => "string"])
```

**Comment by roll** [comment]
But still is there is a way to provide some interface for crating fields? This class could have self-value without `Schema` for type-casting.

Also I use it in test suite (which is coming) extensively:

```yml
- Field - integer

- field=tableschema.Field: [{'name': 'name', 'type': 'integer'}]
- field.type==: 'integer'
- field.format==: 'default'
- field.cast_value: ['', ==: null]
- field.cast_value: [1, ==: 1]
- field.cast_value: ['1', ==: 1]
- field.cast_value: ['3.14', ==: ERROR]
```
